language: php

php:
  - 5.4
  - 5.5

before_script:
  - sh -c "composer require 'cakephp/cakephp-codesniffer:dev-master'"
  - phpenv rehash

script:
  - sh -c "vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./App ./Test ./webroot"

notifications:
  email: false
