language: php

php:
  - 5.4
  - 5.5

env:
  - DB=mysql

before_script:
  - composer self-update
  - composer install
  - mysql -e 'CREATE DATABASE test_database_name;'
  - export DATABASE_TEST_URL="mysql://travis@localhost/test_database_name?encoding=utf8"
  - cd && composer global require 'phpunit/phpunit=3.7.38' && cd -
  - ln -s ~/.composer/vendor/phpunit/phpunit/PHPUnit ./vendor/PHPUnit

script:
  -  ./app/Console/cake test app AllAppTests --stderr

notifications:
  email: false
